# Generated by Django 5.2.5 on 2025-09-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='email',
            field=models.CharField(default='unknown@example.com', max_length=100),
        ),
    ]
