# Generated by Django 5.2.5 on 2025-09-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_item_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
    ]
