# Generated by Django 5.2.5 on 2025-09-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0004_alter_item_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
