# Generated by Django 5.2.5 on 2025-09-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0006_useritem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Useritem',
        ),
        migrations.RemoveField(
            model_name='item',
            name='address',
        ),
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.AddField(
            model_name='item',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='gender',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='phone',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='pincode',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='state',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
