# Generated by Django 5.2.5 on 2025-09-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0007_delete_useritem_remove_item_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='email',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='password',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='username',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
