# Generated by Django 5.2.5 on 2025-09-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0008_alter_item_email_alter_item_name_alter_item_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
