# Generated by Django 5.2.5 on 2025-09-22 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0009_item_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Useritem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.item')),
            ],
        ),
    ]
