# Generated by Django 5.2.5 on 2025-09-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0010_useritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='admin', max_length=100)),
                ('password', models.CharField(default='admin', max_length=100)),
                ('email', models.CharField(default='admin', max_length=100)),
                ('is_staff', models.CharField(default='True', max_length=100)),
                ('is_superuser', models.CharField(default='True', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='password',
        ),
        migrations.RemoveField(
            model_name='item',
            name='phone',
        ),
    ]
