# Generated by Django 5.2.5 on 2025-09-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0011_admin_remove_item_password_remove_item_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='password',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='phone',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
