# Generated by Django 5.2.5 on 2025-09-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0013_delete_admin_remove_useritem_user_useritem_password_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Useritem',
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
