# Generated by Django 5.2.5 on 2025-09-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0014_delete_useritem_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
